name: Mi_Primer_Despliegue
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Ejecutar comando directamente en mi Debian
        run: |
          echo "Â¡Hola desde GitHub Actions!" > ~/Actualizacion de movil.txt
          echo "Se hizo la actualicion en mexico ." >> ~/Actualizacion de movil.txt
          date >> ~/Actualizacion de movil.txt
