name: Mi_Primer_Despliegue
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Ejecutar comando directamente en mi Debian
        run: |
          echo "Â¡Hola desde GitHub Actions!" > ~/hola_mundo.txt
          echo "Se hizo la actualicion en mexico ." >> ~/hola_mundo.txt
          echo "Hola mundo 2 perras." >> ~/hola_mundo.txt
          date >> ~/hola_mundo.txt
