name: Mi_Primer_Despliegue
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Actualizar archivo hola_mundo
        run: |
          echo "Â¡Hola desde GitHub Actions!" > ~/hola_mundo.txt
          echo "Se hizo la actualicion en mexico ." >> ~/hola_mundo.txt
          echo "Hola mundo 2 perras." >> ~/hola_mundo.txt
          date >> ~/hola_mundo.txt

      - name: Info del Sistema
        run: |
          echo "--- INFO DEL SISTEMA ---" >> ~/hola_mundo.txt
          echo "Usuario actual:" >> ~/hola_mundo.txt
          whoami >> ~/hola_mundo.txt
          echo "Memoria disponible" >> ~/hola_mundo.txt
          free -h >> ~/hola_mundo.txt
