name: Despliegue_Desde_Cero
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Generar Reporte de Despliegue
        run: |
          echo "=============" > ~/hola_mundo.txt
          echo "   DESPLIEGUE EXITOSO EN DEBIAN 12" >> ~/hola_mundo.txt
          echo "==========================================" >> ~/hola_mundo.txt
          echo "Fecha de ejecucion: $(date)" >> ~/hola_mundo.txt
          echo "Usuario en Debian: $(whoami)" >> ~/hola_mundo.txt
          echo "Memoria del Servidor:" >> ~/hola_mundo.txt
          free -h >> ~/hola_mundo.txt
